### ISSUE TITLE
Simplification de la fonction nearest_neighbor.R

### ISSUE THREAD

**Issue by Guepardow** [kkmm001/StatApp-Collaborative-Filtering#5]
Dans ce fichier, il y a autant de fonctions que de métriques de similarité. Je ne trouve pas ça très astucieux. Il faudrait rajouter un hyperparamètre "similarité" pour indiquer la similarité.
Ainsi une aura une fonction du type :

``` R
nearest_neighbor = function(user_ID,data.Ratings, similarity){
}
```

PS : on retrouve le même problème pour les fonctions proxi_Users.R et proxi_UsersComplet.R

**Comment by Guepardow** [comment]
Je me suis trompé lors du déplacement de ce fichier. Celui ci va bien dans NeighborhoodBasedAlgorithms et non NaiveAlgorithms.

Par rapport au rajout de la similarité dans les paramètres, je ne suis pas d'accord avec la version actuelle. Je pense qu'il serait plus judicieux de modifier proxi_Users.R puis proxi_UsersComplet.R avant de toucher à nearest_neighobr.R (je ne pense pas que ce fichier survivra tel quel car on cherchera les k plus proches voisins). 

Et l'utilisation de la méthode `switch` me parait plus élégante que `if`.

**Comment by claudiadelgado92** [comment]
J' ai effectué une première modification,
je dois encore  tester la fonction.
Mon problème est que la fonction ne va tourner que pour les deux similarités définies (a savoir Pearson et Euclide) 
Je pense que pour l instant vu qu'on utilise uniquement ces deux similarités cette fonction est suffisante, qu'en pensez vous?

**Comment by Guepardow** [comment]
Pour la similarity, je voyais plus "pearson", "nrmse" (la distance euclidienne divisée par le nombre de films en commun) et "nmae" (la distance manhattan divisée par le nombre de films en commun).
